# -----------------------------------------------------------------------------
# Build & Push (Template 3 - t3-core)
# Builds Docker image from templates/t3-core and pushes a single rolling tag.
# -----------------------------------------------------------------------------

name: Build & Push (Template 3 - t3-core)

on:
  push:
    branches: [ main ]
    paths:
      - 'templates/t3-core/**'
      - '.github/workflows/build-t3.yml'
  workflow_dispatch:

concurrency:
  group: t3-core-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: templates/t3-core
          file: templates/t3-core/Dockerfile
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/stable-diffusion-a1111:t3-core
          platforms: linux/amd64
          provenance: false
          sbom: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
