# -----------------------------------------------------------------------------
# GitHub Actions workflow for Template 1 (t1-bare)
# Builds Docker image from templates/t1-bare and pushes a single rolling tag.
# -----------------------------------------------------------------------------

name: Build & Push (Template 1 - t1-bare)

on:
  push:
    branches: [ main ]
    paths:
      - 'templates/t1-bare/**'
      - '.github/workflows/build-t1.yml'
  workflow_dispatch:

concurrency:
  group: t1-bare-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: templates/t1-bare
          file: templates/t1-bare/Dockerfile
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/stable-diffusion-a1111:t1-bare
          platforms: linux/amd64
          provenance: false
          sbom: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
